### ISSUE TITLE
[BSI][20200603]Missing certificate checks

### ISSUE THREAD

**Issue by BSI-TF-CWA** [corona-warn-app/cwa-testresult-server#65]
Rating: high

The testresult insertion point does not seem to be authenticated.
According to the docu there should be JWT-Token based auth.
We couldn't find an implementation of it yet.

**Comment by alstiefel** [comment]
There are several issues in this ticket.

1) The endpoint for importing test results is open
This issue will be fixed, it was a temporary opening of the firewall to ease testing
2) No JWT validation
This is a wrong documentation/specification. The connection is using mTLS client certificates for authentication, no JWT.
Documentation is fixed in PR
https://github.com/corona-warn-app/cwa-testresult-server/pull/70
